version: '3'
services:
  web:
    image: php:8.2-apache
    volumes:
      - ./appEventos:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
  db:
    image: mysql:8.0
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
  php:
    image: php:8.2-fpm
    volumes:
      - ./appEventos:/var/www/html
    restart: always
    environment:
      - PDO_MYSQL_DSN=mysql:host=db;dbname=mydatabase;charset=utf8mb4
      - PDO_MYSQL_USERNAME=myuser
      - PDO_MYSQL_PASSWORD=mypassword
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: myuser
      PMA_PASSWORD: mypassword
    ports:
      - "8080:80"
    depends_on:
      - db